spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo2403?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 20
        min-idle: 0
#  security:
#    user:
#      name: admin
#      password: admin
  servlet:
    .multipart:
      .max-file-size: 10MB
      .max-request-size: 10MB


  web:
    resources:
      static-locations: file:/E:/fileStorage/

# mybatisPlus配置
mybatis-plus:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

# lombok配置
lombok:
  equalsAndHashCode:
    callSuper: true

file:
  storage: "E:/fileStorage"
  files: "/files"


