spring:
  profiles:
    active: dev

# mybatisPlus配置
mybatis-plus:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

# lombok配置
lombok:
  equalsAndHashCode:
    callSuper: true




